# Generated by Django 3.1.7 on 2021-06-19 14:18

import apps.users_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=45)),
                ('first_name2', models.CharField(max_length=45)),
                ('last_name1', models.CharField(max_length=45)),
                ('last_name2', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, validators=[apps.users_app.models.validarEmail])),
                ('password', models.CharField(max_length=100, validators=[apps.users_app.models.ValidarLongitudPassword])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tribunal', models.CharField(default='00', max_length=6)),
                ('name_court', models.CharField(default='no asigando', max_length=45)),
                ('comuna', models.CharField(default='no asigando', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=45, validators=[apps.users_app.models.ValidarLongitud])),
                ('first_name2', models.CharField(max_length=45, validators=[apps.users_app.models.ValidarLongitud])),
                ('last_name1', models.CharField(max_length=45, validators=[apps.users_app.models.ValidarLongitud])),
                ('last_name2', models.CharField(max_length=45, validators=[apps.users_app.models.ValidarLongitud])),
                ('address', models.CharField(max_length=255, validators=[apps.users_app.models.ValidarLongitud])),
                ('rut', models.CharField(max_length=25, validators=[apps.users_app.models.ValidarRut])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_promissory_notes', models.CharField(max_length=45)),
                ('final_date', models.DateField(validators=[apps.users_app.models.Validar_Fecha])),
                ('mount_to_pay', models.CharField(max_length=255, validators=[apps.users_app.models.Validar_Monto_a_Pagar])),
                ('num_operation', models.CharField(max_length=255)),
                ('suscription_date', models.DateField(validators=[apps.users_app.models.Validar_Fecha])),
                ('demand_amount', models.CharField(max_length=255, validators=[apps.users_app.models.Validar_Monto_Demandado])),
                ('cause_rol', models.CharField(default='no asigando', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_court_lawsuits', to='users_app.court')),
                ('current_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendant_lawsuit', to='users_app.defendant')),
            ],
        ),
        migrations.CreateModel(
            name='Lawsuit_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(default='escritura creada', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=45)),
                ('first_name2', models.CharField(max_length=45)),
                ('last_name1', models.CharField(max_length=45)),
                ('last_name2', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30, validators=[apps.users_app.models.validarEmail])),
                ('password', models.CharField(max_length=100, validators=[apps.users_app.models.ValidarLongitudPassword])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_user', to='users_app.usertype')),
                ('users_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_create', to='users_app.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='LawsuitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuit_change', to='users_app.user')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuit_current_state', to='users_app.lawsuit_state')),
                ('lawsuit_associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuit_history', to='users_app.lawsuit')),
                ('past_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuit_past_state', to='users_app.lawsuit_state')),
            ],
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='current_demand_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_demand_lawsuits', to='users_app.lawsuit_state'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='lawsuit_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administrate_lawsuit', to='users_app.user'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='defendant_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_defendant', to='users_app.user'),
        ),
    ]
