# Generated by Django 3.1.7 on 2021-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuithistory',
            name='docfile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
